baseURL = "/"
languageCode = "en-us"
title = "block scope"
theme= "awayhugo"
copyright = "Copyright 2015-{year}"
homepage = "/"
sectionPagesMenu = "main"
[params]
   env = 'dev'
[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
