baseURL = "/"
languageCode = "en-us"
title = "block scope"
theme= "awayhugo"
copyright = "Copyright 2015-{year}"
homepage = "/"
sectionPagesMenu = "main"
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = "series"
    weight = 100
[taxonomies]
  category = "categories"
  tag = "tags"
[params]
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
[menu]
[[menu.main]]


